name: React Native E2E Tests (Android)

on:
    pull_request:
    push:
        branches: [trunk]

jobs:
    test:
        runs-on: macos-latest
        strategy:
            matrix:
                native-test-name: [gutenberg-editor-initial-html]

        steps:
            - name: checkout
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - run: npm install

            - uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
              if: always()
              with:
                  name: package-lock-json
                  path: package-lock.json

            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
