name: React Native E2E Tests (iOS)

on:
    pull_request:
        paths-ignore:
            - '**.md'
    push:
        branches: [trunk]
        paths-ignore:
            - '**.md'

jobs:
    test:
        runs-on: macos-latest
        strategy:
            matrix:
                native-test-name: [gutenberg-editor-gallery]

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                node-version: 14.x

            - name: Restore npm cache
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

            - run: npm ci

            - name: Prepare build cache key
              run: find package-lock.json packages/react-native-editor/ios packages/react-native-aztec/ios packages/react-native-bridge/ios -type f -print0 | sort -z | xargs -0 shasum | tee ios-checksums.txt

            - name: Restore build cache
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  path: packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app
                  key: ${{ runner.os }}-ios-build-${{ hashFiles('ios-checksums.txt') }}

            - name: Restore pods cache
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  path: |
                      packages/react-native-editor/ios/Pods
                      ~/Library/Caches/CocoaPods
                      ~/.cocoapods/repos/trunk
                      packages/react-native-editor/ios/vendor
                  key: ${{ runner.os }}-pods-${{ hashFiles('packages/react-native-editor/ios/Gemfile.lock') }}-${{ hashFiles('packages/react-native-editor/ios/Podfile.lock') }}-${{ hashFiles('package-lock.json') }}

            - name: Bundle iOS
              run: npm run native test:e2e:bundle:ios

            - name: Switch Xcode Version
              run: sudo xcode-select --switch /Applications/Xcode_12.app

            - name: Build (if needed)
              run: test -e packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app/gutenberg || npm run native test:e2e:build-app:ios

            - name: Run iOS Device Tests
              run: TEST_RN_PLATFORM=ios npm run native device-tests:local  ${{ matrix.native-test-name }}

            - name: Prepare build cache
              run: rm packages/react-native-editor/ios/build/GutenbergDemo/Build/Products/Release-iphonesimulator/GutenbergDemo.app/main.jsbundle

            - uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
              if: always()
              with:
                  name: ios-screen-recordings
                  path: packages/react-native-editor/ios-screen-recordings
